server:
  port: 8083

feign:
  okhttp:
    enabled: true # 开启okhttp连接池支持

hm:
  db:
    database: hm-cart # 数据库名称
  swagger:
    title: "购物车服务接口文档" # swagger标题
    package: com.hmall.cart.controller # swagger扫描的包路径