server:
  port: 8080

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:   #无需登陆也可以访问的网址
      - /search/**
      - /users/login
      - /items/**
      - /hi